# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Milo < Formula
  desc "milo CLI — single-host PaaS client"
  homepage "https://github.com/callmemhz/milo"
  version "0.3.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/callmemhz/milo/releases/download/v0.3.1/milo_0.3.1_darwin_amd64.tar.gz"
      sha256 "40dfb35afe9de322d8e0f65a903936689abd90cbc814b0be11a623e52af49115"

      define_method(:install) do
        bin.install "milo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/callmemhz/milo/releases/download/v0.3.1/milo_0.3.1_darwin_arm64.tar.gz"
      sha256 "c9b1c72db5d8353286cde2dbea6d3d6bee893764aee5948cae7276e9786b7e77"

      define_method(:install) do
        bin.install "milo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/callmemhz/milo/releases/download/v0.3.1/milo_0.3.1_linux_amd64.tar.gz"
      sha256 "b90f9988490b3c8d057ef97a3798478dbd762a4c57b65caa575c3a3f1f6ce954"
      define_method(:install) do
        bin.install "milo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/callmemhz/milo/releases/download/v0.3.1/milo_0.3.1_linux_arm64.tar.gz"
      sha256 "4317513677a4ce3f5410dde6ab3e65037bd958ff78fb2192ec437ddeace27327"
      define_method(:install) do
        bin.install "milo"
      end
    end
  end

  test do
    system "#{bin}/milo", "version"
  end
end
