# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MiloAppsKit < Formula
  desc "milo-apps-kit CLI — single-host PaaS client"
  homepage "https://github.com/callmemhz/milo-apps-kit"
  version "0.2.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/callmemhz/milo-apps-kit/releases/download/v0.2.1/milo-apps-kit_0.2.1_darwin_amd64.tar.gz"
      sha256 "cab4ac9b78516f82fa86569329c5346d5038289e7bbf99848105b887e7ad1905"

      define_method(:install) do
        bin.install "milo-apps-kit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/callmemhz/milo-apps-kit/releases/download/v0.2.1/milo-apps-kit_0.2.1_darwin_arm64.tar.gz"
      sha256 "67e6b9d289ec4e335250c74822a69be24e5cfad22b69df363317911ec5810d6f"

      define_method(:install) do
        bin.install "milo-apps-kit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/callmemhz/milo-apps-kit/releases/download/v0.2.1/milo-apps-kit_0.2.1_linux_amd64.tar.gz"
      sha256 "6ae7f1cae4cc7456956247b905cb18fd1858a8333297b80ecd949c6d3ebecc76"
      define_method(:install) do
        bin.install "milo-apps-kit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/callmemhz/milo-apps-kit/releases/download/v0.2.1/milo-apps-kit_0.2.1_linux_arm64.tar.gz"
      sha256 "8c255ffa03f573ec3d4bc6534576c8c41054e37d8c98cf439371a45d608366fe"
      define_method(:install) do
        bin.install "milo-apps-kit"
      end
    end
  end

  test do
    system "#{bin}/milo-apps-kit", "version"
  end
end
